name=7Semi LIS3DH
version=1.0.0
author=7Semi <info@7semi.com>
maintainer=7Semi <info@7semi.com>
sentence=Arduino library for LIS3DH 3-axis accelerometer with I2C and SPI support.
paragraph=This library supports LIS3DH accelerometer over I2C and SPI with features like raw and g-unit acceleration, INT1/INT2 interrupts, ADC readings, and temperature measurement.
category=Sensors
url=https://github.com/7semi-solutions/7Semi-LIS3DH-3-axis-acceleromet-Arduino-Library
architectures=*
includes=7Semi_LIS3DH.h
